export const blogs = [
    {
      id: "1",
      title: "Prvi blog",
      description: "Opis o tome kako da započnete blogovanje.",
      imageUrl: "https://picsum.photos/300/200?random=1",
    },
    {
      id: "2",
      title: "Drugi blog",
      description: "Saveti za produktivnost u svakodnevnom životu.",
      imageUrl: "https://picsum.photos/300/200?random=2",
    },
    {
      id: "3",
      title: "Tehnologija danas",
      description: "Kako tehnologija menja naše svakodnevne živote.",
      imageUrl: "https://picsum.photos/300/200?random=3",
    },
    {
      id: "4",
      title: "Putopisi i avanture",
      description: "Najlepše destinacije koje treba posetiti.",
      imageUrl: "https://picsum.photos/300/200?random=4",
    },
    {
      id: "5",
      title: "Recepti za početnike",
      description: "Jednostavni recepti koje možete isprobati kod kuće.",
      imageUrl: "https://picsum.photos/300/200?random=5",
    },
    {
      id: "6",
      title: "Fotografija za početnike",
      description: "Kako savladati osnove fotografije.",
      imageUrl: "https://picsum.photos/300/200?random=6",
    },
    {
      id: "7",
      title: "Minimalizam u praksi",
      description: "Prednosti i saveti za minimalistički životni stil.",
      imageUrl: "https://picsum.photos/300/200?random=7",
    },
    {
      id: "8",
      title: "Digitalni marketing",
      description: "Kako izgraditi online prisustvo za vaš brend.",
      imageUrl: "https://picsum.photos/300/200?random=8",
    },
    {
      id: "9",
      title: "Razvijanje mobilnih aplikacija",
      description: "Kreiranje aplikacija za Android i iOS.",
      imageUrl: "https://picsum.photos/300/200?random=9",
    },
    {
      id: "10",
      title: "Zdrav način života",
      description: "Kako održavati balans između posla i zdravlja.",
      imageUrl: "https://picsum.photos/300/200?random=10",
    },
    {
      id: "11",
      title: "Modni trendovi 2023",
      description: "Šta je popularno u svetu mode ove godine.",
      imageUrl: "https://picsum.photos/300/200?random=11",
    },
    {
      id: "12",
      title: "Umetnost i dizajn",
      description: "Inspiracija za kreativne projekte.",
      imageUrl: "https://picsum.photos/300/200?random=12",
    },
    {
      id: "13",
      title: "Psihologija i samopouzdanje",
      description: "Kako izgraditi samopouzdanje kroz iskustva.",
      imageUrl: "https://picsum.photos/300/200?random=13",
    },
    {
      id: "14",
      title: "Domaći projekti",
      description: "Uputstva za „Uradi sam” projekte.",
      imageUrl: "https://picsum.photos/300/200?random=14",
    },
    {
      id: "15",
      title: "Gledanje filmova i serija",
      description: "Preporuke za najbolje serije i filmove.",
      imageUrl: "https://picsum.photos/300/200?random=15",
    },
    {
      id: "16",
      title: "Fokus na mentalno zdravlje",
      description: "Kako očuvati mentalno zdravlje u stresnim vremenima.",
      imageUrl: "https://picsum.photos/300/200?random=16",
    },
    {
      id: "17",
      title: "Ljudi i priče iz sveta",
      description: "Interesantne priče o ljudima širom sveta.",
      imageUrl: "https://picsum.photos/300/200?random=17",
    },
    {
      id: "18",
      title: "Pametno ulaganje novca",
      description: "Saveti za upravljanje ličnim finansijama.",
      imageUrl: "https://picsum.photos/300/200?random=18",
    },
    {
      id: "19",
      title: "Školski trikovi",
      description: "Kako lakše učiti i organizovati školske obaveze.",
      imageUrl: "https://picsum.photos/300/200?random=19",
    },
    {
      id: "20",
      title: "Ekološki život",
      description: "Život u skladu sa prirodom i reciklaža.",
      imageUrl: "https://picsum.photos/300/200?random=20",
    },
  ];